### ISSUE TITLE
TypeError: Got secondary option for non boolean flag.

### ISSUE THREAD

**Issue by bdseal** [rotemtzaban/STIT#8] opened 2022-02-16 13:33 UTC
>Traceback (most recent call last):
  File "train.py", line 60, in <module>
    @click.option('--use_wandb/--no_wandb', default=False)
  File "/home/xwh/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/xwh/anaconda3/lib/python3.7/site-packages/click/core.py", line 1601, in __init__
    raise TypeError('Got secondary option for non boolean flag.')
TypeError: Got secondary option for non boolean flag.

Got an error. Anyone knows how to fix this?

**Comment by rotemtzaban** [comment] 2022-02-16 14:25
@bdseal 
What version of click do you have?
This similar [issue](https://github.com/pallets/click/issues/1287) is solved by removing ```type=bool``` from the option declaration.
Though from the stack trace it seems like you've tried that.

**Comment by bdseal** [comment] 2022-02-16 14:42
@rotemtzaban thank you for your prompt response. I have googled and tried that but it didn't work for me. Alternatively,  I run the codes using google colab.

**Comment by rotemtzaban** [comment] 2022-02-16 14:52
@bdseal 
Are you simply running the scripts with Google Colab? I haven't tried it but I would expect it to work.
Can you check the version of click you have, say with running ```pip freeze | grep click```?
Maybe even try to upgrade click to the latest version if possible.

**Comment by rotemtzaban** [comment] 2022-02-16 14:53
I can also try later to check the notebook myself, If you want to send me a copy I'll try to look over it

**Comment by rotemtzaban** [comment] 2022-02-16 15:20
@bdseal 
Oh OK, Thanks for the clarification, glad to know it works well on Colab.
I've reproduced the issue on my server with click==7.0, and it seems to be fixed by removing all the ```type=bool``` from flag options.
e.g. make sure to remove it from the use_dlib and use_locality_reg flags as well.
Alternatively, upgrading click to 7.1 or higher also seems to work for me

**Comment by bdseal** [comment] 2022-02-16 15:29
Thanks. Considering that #7 is also caused by the package version, it might be helpful to add a requirements.txt. 

Besides, [this](https://github.com/rotemtzaban/STIT/files/8081109/STIS.zip) is a simple Colab notebook I used. Maybe it would be helpful for those who want to try STIS on Colab like me before you released the official one.

**Closed** 2022-02-17 17:51 UTC
